### ISSUE TITLE
Discussion: NBHM and NBHS int key versions

### ISSUE THREAD

**Issue by guidomedina** [JCTools/JCTools#110] opened 2016-04-29 11:02 UTC
Hi @cliffclick 

Is there a reasoning for not having an int version of NBHM and NBHS?

Is there something I'm not seeing for example, all `hashCode` and  `==` operation elevated to `long` hence making `int` versions defy the GC purpose of `long` variants?
Or if this has been discussed before point me to the discussion please.

If there isn't any side effect to have `int` variants of these two I see myself using them, a lot.

**Comment by cliffclick** [comment] 2016-04-29 16:06
Because there's not much gain over the 'long' version.  There's a giant 
gain over both 'Int' and 'Long' key'd HashMaps - because a Long or Int 
needs 2 header words, and 1 payload word (and maybe a pad).

Time will be nearly the same, modulo space/d-cache effects.

Space math: Typically you pay a 50% load factor, plus a Value pointer 
and either a long or int, plus for tiny tables the metadata counts.  
Per-table overheads are something like 2 object headers, and a few 
pointers: about 64 bytes.  Assuming a 64-bit JVM, and discounting the 
overhead for the Value object (so just Key space overheads), the 
per-entry math is:

Long: ((8+2*8+8)+8)*2 = 80 bytes
long: (8 + 8 )*2 = 32 bytes
int: (4 + 8 )*2 = 24 bytes

Any speed gains will come from a table which fits in L1 cache if 'int' 
and not if 'long', and you don't have any i-cache issues because you are 
touching both kinds of tables hence need 2 copies of NBHM in the i-cache.

There's no other downside (other than maintenance) to having both versions.

Cliff

**Comment by guidomedina** [comment] 2016-04-29 17:33
Another case is where your key IDs are `Integer`, maybe I'm just too paranoid thinking that millions of up/down casts is not worth if you have the `int` type.

It is strange that Agrona has only `int` types _(which I use for non-concurrent or pre-created caches - 100% read)_ and NBHM `long` types, I believe that if there isn't any downside besides maintenance it would be worth having them.

**Comment by guidomedina** [comment] 2016-04-29 17:39
@cliffclick off topic: I watched your presentation at InfoQ: Java vs C++, that was nice :D

**Comment by cliffclick** [comment] 2016-04-29 17:40
If you go to the trouble of using the 'long' version of NBHM - and make 
it stick (e.g. don't accidentally autobox to 'Long') - then it's really 
trivial to use it for 'Integer' cases as well. The only bonus in 
usability is a few accidental-autobox opportunities are missed by making 
function calls typed as 'int' vs 'long'.

If you already have 'int's, calling the 'long' version of NBHM will 
almost the same performance as a custom 'int' version, and no 
auto-boxing in sight.

If you already have 'Integer's, and you are trying to use either the 
'long' version of NBHM or a hypothetical 'int' version, so are forced 
into some autoboxing, and it's the same amount of it either way.

In all cases the danger is silent autoboxing with attendant huge 
performance costs, and the issue is how do you arrange the code so you 
can maintain the good performance.

Cliff

**Comment by RichardWarburton** [comment] 2016-04-29 18:34
@guidomedina - one clarification, Agrona actually has Int and Long versions of its collections - we generate the Long versions from the Int template. But thanks for your comment, because I now realise that this isn't a well documented fact!

**Comment by guidomedina** [comment] 2016-04-30 09:15
@RichardWarburton thanks for your clarifying comment, it is good to know, I wonder now if a similar approach (code generation) could be applied to `NonBlockingHashMapLong` and `NonBlockingHashSetLong` to generate their `int` counterparts.

In such way you would only have to maintain one version, I still think it is worth the effort, just like you thought it was worthy for Agrona.

Or maybe I'm just behaving like a kid when he wants a toy to play with :(

**Comment by guidomedina** [comment] 2016-04-30 09:18
But, you already have the 'int' version of a `Set`
https://github.com/JCTools/JCTools/blob/master/jctools-experimental/src/main/java/org/jctools/maps/NonBlockingSetInt.java

It just needs the concurrent map.

**Comment by cliffclick** [comment] 2016-04-30 16:29
The long version doesn't make sense - because space is proportional to 
the max value in the set, which can be insane for longs.  Practically 
bit sets are limited to a few hundreds of megabytes which makes the max 
value fit in an int in any case.

Cliff

**Comment by nitsanw** [comment] 2016-05-29 16:20
I think this has been clarified, closing.

**Closed by nitsanw** 2016-05-29 16:20 UTC
Labels: question
