### ISSUE TITLE
ConcurrentMap::compute default implementation bug results in NPE when invoked concurrently on NBHM

### ISSUE THREAD

**Issue by adamretter** [JCTools/JCTools#232] opened 2019-03-02 13:03 UTC
If I understand correctly, `NonBlockingHashMap` can be used as a drop-in replacement for `ConcurrentHashMap`.

Unfortunately, I have code that works when using Java's `ConcurrentHashMap` but when I try and replace it with `NonBlockingHashMap` I get a `NullPointerException`:

```
java.lang.NullPointerException
	at org.jctools.maps.NonBlockingHashMap.putIfMatch(NonBlockingHashMap.java:379)
	at org.jctools.maps.NonBlockingHashMap.remove(NonBlockingHashMap.java:340)
	at java.util.concurrent.ConcurrentMap.compute(ConcurrentMap.java:426)
	at org.exist.storage.lock.LockTable.decrementAcquired(LockTable.java:430)
```

I am not certain but this seems to look like a concurrent modification issue. You can find my code here - https://github.com/adamretter/exist/blob/exp-nonblockinghashmap/exist-core/src/main/java/org/exist/storage/lock/LockTable.java#L430

A unit test which uses multiple threads and reveals the fault - https://github.com/adamretter/exist/blob/exp-nonblockinghashmap/exist-core/src/test/java/org/exist/dom/persistent/BasicNodeSetTest.java#L79

**Comment by franz1981** [comment] 2019-03-03 10:58
Looking at the stack-trace:

- `NonBlockingHashMap::putIfMatch`  could throw NPE only if `oldVal` or `newVal` are `null` at that line of code
- for `NonBlockingHashMap::remove` `newVal` is `TOMBSTONE` ie `oldVal` is `null`
- on `ConcurrentMap::compute`,  `remove` can be called only if `oldValue != null || containsKey(key)` ie `containsKey(key)` is `true` and `oldValue = null` 
- `oldValue` has been obtained from `get(key)` ie initially, there was no mapping for that `key`

If a racing put will add a (previously not existing) mapping between the `get(key)` call and the `containsKey(key)` check, the `NonBlockingHashMap::remove`  will fail with NPE. 
I believe that `NonBlockingHashMap` should implement its own `compute` behaviour (as `ConcurrentHashMap` has done), maybe relaxing the `remove` when called on it.

Just as a note, looking at `ConcurrentHashMap::compute` javadoc:
![image](https://user-images.githubusercontent.com/13125299/53694124-6c2af500-3daa-11e9-83ba-3939e7e6cc2b.png)
If both `oldValue` and `newValue` are `null` it should return `null`, while the code of `ConcurrentMap::compute` is relying on `containsKey(key)`too, leading to call `NonBlockingHashMap::remove`.

**Comment by adamretter** [comment] 2019-03-03 13:23
@franz1981 Okay thanks, that makes a lot of sense.

So should this be considered a bug in `NonBlockingHashMap`?

**Comment by franz1981** [comment] 2019-03-03 15:16
@adamretter Not sure. 
If you look at the `ConcurrentHashMap::remove(Object, Object)` javadoc, it is actually more permissive then `NonBlockingHashMap::remove(Object, Object)` ie it won't NPE on a null `value`, while `NonBlockingHashMap` yes.
Let me try a fix and if it will pass both the test and your use case, maybe it will be merged (I don't have the power to do that :))

**Comment by franz1981** [comment] 2019-03-13 17:06
@adamretter any news on this one?

**Comment by nitsanw** [comment] 2019-03-13 21:54
The `Map` javadoc is very confusing where `null` keys or values are concerned, and allows for optional throwing of NPE, which the ConcurrentMap default implementation should in theory be defensive about. Having said all that, I think @franz1981 solution is a good starting point to verify this will work for @adamretter so please respond.

**Comment by adamretter** [comment] 2019-03-14 05:28
Utilising the code (below), eliminates the NPE. However, the behaviour is still different from that of `ConcurrentHashMap` in so far as I am seeing a lot of unexpected `null` values for `v` in the lambda passed to `compute`.

With `ConcurrentHashMap` I never get an unexpected `null` value for `v` in compute. I think that might be due to the happens-before relationship of put and compute. So I am not sure if this suggested behaviour for compute is actually correct...

```java
       @Override
        public TypeV compute(TypeK key,
                       BiFunction<? super TypeK, ? super TypeV, ? extends TypeV> remappingFunction) {
            Objects.requireNonNull(remappingFunction);
            TypeV oldValue = get(key);
            for(;;) {
                TypeV newValue = remappingFunction.apply(key, oldValue);
                if (newValue == null) {
                    // delete mapping
                    if (oldValue != null || containsKey(key)) {
                        // something to remove
                        if (oldValue != null && remove(key, oldValue)) {
                            // removed the old value as expected
                            return null;
                        }

                        // some other value replaced old value. try again.
                        oldValue = get(key);
                    } else {
                        // nothing to do. Leave things as they were.
                        return null;
                    }
                } else {
                    // add or replace old mapping
                    if (oldValue != null) {
                        // replace
                        if (replace(key, oldValue, newValue)) {
                            // replaced as expected.
                            return newValue;
                        }

                        // some other value replaced old value. try again.
                        oldValue = get(key);
                    } else {
                        // add (replace if oldValue was null)
                        if ((oldValue = putIfAbsent(key, newValue)) == null) {
                            // replaced
                            return newValue;
                        }

                        // some other value replaced old value. try again.
                    }
                }
            }
        }
```

**Comment by franz1981** [comment] 2019-03-14 07:50
> With ConcurrentHashMap I never get an unexpected null value for v in compute

It makes sense: I have provided a version that actually is compliant with `ConcurrentMap::compute` contract, not `ConcurrentHashMap`.

> I think that might be due to the happens-before relationship of put and compute

It is actually due to how `ConcurrentHashMap` is implemented: it basically `lock` a set of keys (semplicistic but give the idea), that means that until you won't finish the `remappingFunction.apply(key, oldValue)` it won't release the lock and you cannot `compute` other keys belonging to the locked set. 

> So I am not sure if this suggested behaviour for NonBlockingHashMap's compute is actually correct...

Given that `NonBlockingHashMap` implements `ConcurrentMap` and is not a `ConcurrentHashMap` I think that is acceptable, but probably @cliffclick could give his view of this one.
I'm not one of the author of this library, so this is just a personal opinion: I let @nitsanw put his word on this :+1:

**Comment by nitsanw** [comment] 2019-03-14 08:48
OK, let's play JMM lawyers! :-P
Here's `compute` javadoc:
```
     * The default implementation is equivalent to performing the following
     * steps for this {@code map}, then returning the current value or
     * {@code null} if absent:
     *
     * <pre> {@code
     * V oldValue = map.get(key);
     * V newValue = remappingFunction.apply(key, oldValue);
     * if (oldValue != null ) { 
     *    if (newValue != null)
     *       map.replace(key, oldValue, newValue);
     *    else
     *       map.remove(key, oldValue);
     * } else {
     *    if (newValue != null)
     *       map.putIfAbsent(key, newValue);
     *    else
     *       return null;
     * }
     * }</pre>
     *
     * The default implementation may retry these steps when multiple
     * threads attempt updates including potentially calling the remapping
     * function multiple times.
     *
     * <p>This implementation assumes that the ConcurrentMap cannot contain null
     * values and {@code get()} returning null unambiguously means the key is
     * absent. Implementations which support null values <strong>must</strong>
     * override this default implementation.
```
So from the above I am leaning towards saying the default implementation violates the doc, as "This implementation assumes that the ConcurrentMap cannot contain null values" implies that `remove(key, null)` throwing an NPE is expected behavior(see the Map javadoc). The `implementation spec` in the comment does not accommodate the conflicted state of `oldVal == null && containsKey(key)` which is only possible for maps that do not allow null values (the state can "seen" due to concurrent modification, but the redundant check makes our view on the mapping inconsistent instead of using replace/remove to do the right thing atomically).

**Comment by nitsanw** [comment] 2019-03-14 08:57
Might be related, but AFAICT you are working under the assumption that compute is called once per successful insert, but the doc clearly suggests this is not the case("including potentially calling the remapping function multiple times"). Your increment method can be called spuriously AND concurrently.

**Comment by franz1981** [comment] 2019-03-14 09:10
Thanks for the clarification @nitsanw :100:

**Comment by adamretter** [comment] 2019-03-14 13:09
I guess I was assuming that I could use it as a drop-in-replacement for `ConcurrentHashMap`because the Javadoc in `NonBlockingHashMap` says:

> It provides identical correctness properties as ConcurrentHashMap
From: https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/maps/NonBlockingHashMap.java#L31

I guess I interpreted that to mean - "exhibits the same behaviour of methods", where perhaps I should not have ;-)

**Comment by cliffclick** [comment] 2019-03-14 21:25
NBHM is indeed not a wrapper around CHM, but instead implements CM with 
a very different implementation than CHM.

NBHM does not (now) have a 'compute' call directly, so it defaults to 
the one in CM.  As alluded to by Nitsan, this pretty much implies the 
remappingFunction will be called multiple times.

I do not have any stack traces in front of me to look at, so I don't 
know where you saw an NPE thrown but it's pretty clear that the 
remappingFunction can be handed a null if the key goes missing any time 
during the update loop.  I.e., testing the key exists before calling 
'compute' is no guarantee, because another thread can remove it while 
the remappingFunction() is busy computing (or indeed anytime in the 
for(;;;) loop in the default code).


Cliff

**Comment by nitsanw** [comment] 2019-03-15 07:56
@adamretter I understand the usecase you are after, and I've read through the CHM implementation. There's no way I can see (though I only gave it 5 minutes of thinking, so may well be wrong, @cliffclick feedback welcome) to support a "compute only calls mapping once" feature without making the algorithm blocking. We can CAS in a dummy value to reserve the entry and then call the mapping method, but if mapping function then blocks (or the thread is suspended for any other reasons) all other threads doing put/compute/remove will also block. This is a big deal for a NonBlockingHashMap, so I'm reluctant to go down that path.
Having said that, the NPE is fixable, though in your case will just hide a broken behavior. It's a bug in the CM default implementation (IMO) and we can provide an alternative that is truer to the doc. I'll fix it in the near future.

**Comment by cliffclick** [comment] 2019-03-15 18:21
Yes, **impossible** to both be non-blocking and "only compute once" - 
for all machines, and all implementations of all hashmaps.

If 64 cores on a 64-way machine all ask for the same value, then either 
they all compute it "for themselves" (redundant computations), or they 
let somebody else compute it for them... and have to await that other 
core's efforts - i.e., block.

Only 1 computation is stored of course, but the expectation is that the 
computations can be computed repeatedly as needed. Generally this means 
they should be "pure", but no requirement.  I often add Atomic counters 
to track the total exec count (compared with total installs into the 
HashMap tells me the "duplicate effort" factor).

Cliff

**Comment by adamretter** [comment] 2019-03-16 04:32
Perhaps I should explain from basics my use-case and then someone might be able to comment on another approach I could take, or if it is possible for me to handle nulls in compute.

Basically I have a pool of threads (20) that are producing events. These events are about taking locks elsewhere in the system. A single thread for a resource X always produces events in this sequence:

```
Attempt(X)
Acquired(X)
Released(X)
```

or

```
Attempt(X)
AttemptFailed(X)
```

or (where re-entrant locks are used):

```
Attempt(X)
Acquired(X)
Attempt(X)
Acquired(X)
Released(X)
Released(X)
```

My goal is to keep two tables, one of attempts and one of acquisitions. For those tables I was using a concurrent map which holds values like this:

```
private static class LockEntry {
        final String resourceName;
        final LockType lockType;
        final LockMode lockMode;
        final String ownerThreadName;

        private final AtomicInteger count = new AtomicInteger(1);
        private @Nullable final List<StackTraceElement[]> stackTraces;

        @Override
        public int hashCode() {
            return hashCode(this);
        }

        public static int hashCode(final String id, final LockType lockType, final LockMode lockMode, final String owner) {
            int result = resourceName.hashCode();
            result = 31 * result + lockType.hashCode();
            result = 31 * result + lockMode.hashCode();
            result = 31 * result + ownerThreadName.hashCode();
            return result;
        }
}
```

My maps look like `Map<Integer, LockEntry>`. The key is actually the hash code of the LockEntry object. This is done because the listener that receives the locking events does not receive LockEntry objects, but rather a series of fields from which it can build a LockEntry object from if it needs to, e.g.

```
private void event(final LockAction.Action action, final long groupId, final String id, final LockType lockType, final LockMode mode, final int count) {
    final Thread currentThread = Thread.currentThread();
    final String ownerThreadName = currentThread.getName();


...

    switch (action) {
        case Attempt:
            final LockEntry attemptEntry = new LockEntry(id, lockType, mode, threadName, stackTrace);
            attempting.put(attemptEntry.hashCode(), attemptEntry);
            break;

        case AttemptFailed:
                final LockEntry attemptFailedEntry  = attempting.remove(LockEntry.hashCode(id, lockType, mode, threadName));
                if (attemptFailedEntry == null) {
                    LOG.error("No entry found when trying to remove failed attempt for: id={}" + id);
                }
                break;

        case Acquired:
                final LockEntry acquiredEntry = attempting.remove(LockEntry.hashCode(id, lockType, mode, threadName));
                if (acquiredEntry == null) {
                LOG.error("No entry found when trying to migrate attempt to acquired for: id={}" + id);
                        break;
                }

                acquired.compute(acquiredEntry.hashCode(), (_k, v) -> {
                        if (v == null) {
                                v = acquiredEntry;
                        } else {
                                v.incrementCount();
                                v.addStackTrace(acquiredEntry.stackTraces == null ? null : acquiredEntry.stackTraces.get(0));
                        }
                        return v;
                });
                break;

        case Released:
                 acquired.compute(LockEntry.hashCode(id, lockType, mode, threadName), (_k, v) -> {
                        if (v.getCount() == 1) {
                                // shortcut! no need to decrement, just remove the entry
                                return null;
                         }

                        v.decrementCount();
                        v.removeLastStackTrace();

                         return v;
                });
                break;
}
```

So the goal is to maintain the `attempting` and `acquired` tables. For updating events each LockEntry will only ever be written by the thread of `ownerThreadName`. Other threads can attempt to read the entries from the `attempting` or `acquired` tables at any time for the purposes of reporting.

I had expected that if a thread placed a LockEntry in the NBHM using `put`, then when the same thread subsequently calls `compute`, it would not see a `null`. I think that is fundamentally the problem I am dealing with (assuming I haven't some silly bug in my code).

**Comment by cliffclick** [comment] 2019-03-16 06:34
You are not using LockEntry's as keys, instead you are using 
LockEntry.hashCode as the key.
If you have any hashCode collisions from unrelated locks, they can 
remove the LockEntry you are looking for.

I suggest you use LockEntry's directly as keys, and add a matching 
equals() call to your existing hashCode().

This is a user-bug, and is not related to the compute() semantics.

Cliff

**Comment by adamretter** [comment] 2019-03-16 07:50
@cliffclick Thanks I understand your concern with regards to hash-collisions. However I think I might have muddied the waters. Sorry.

The NPE I originally reported was coming from code where I did not use the hash code as a key. The subsequent nulls in `compute` were also from not using a hash code as a key.

Where I have used a hash code, I have actually run a check across my test to ensure that for my test dataset there are no hash collisions. Obviously... I still need to to do better for code that will run outside of the "test" ;-)

**Comment by cliffclick** [comment] 2019-03-16 16:20
:-)

Well, if you want some help diagnosing a bug, it pays to hand out all 
the relevant code...  like, please hand out the entire code (missing 
pieces in the example looked important), and also the stack trace.

If you think you have a 'perfect' hash function, then I encourage you to 
both document AND assert for such...
but I also have to ask why?  You're only avoiding the key-equals call, 
which is pretty darned cheap.
Also noting that your hashCode depends on the thread-name, which you do 
not control.
The JVM is totally allowed to play adversarial and choose thread names 
to force a hash collision.
e.g. same resource, same lock, same mode, 2 unique threads whose 
hashCode's collide.

Cliff

**Comment by adamretter** [comment] 2019-03-19 07:30
@cliffclick Okay I have moved on a bit with my implementation, I am no longer using integer keys of hash codes. I also no longer use `compute`... just `put`, `get`,  and `remove`

I am wondering if NBHM permits the use of mutable keys? As I create many millions of short-lived entries in the map, to reduce object allocation and in particular GC I have been experimenting with pre-allocating a pool of objects and then recycling key objects when they are finished with.

Only when I use mutable keys, I see an issue where a `put(K, obj)`, and then a subsequent `remove(K)` returns `null`, although using the debugger I can indeed see that the entry is actually present in the NBHM.

I have created a standalone runnable project and extracted as little code as I could from our main project to reproduce the problem. This code is single single threaded and still shows my issue - https://github.com/adamretter/nonblockinghashmaptest

If you look here (https://github.com/adamretter/nonblockinghashmaptest/blob/master/src/main/java/nbhm/Test1.java#L386) you will see that both with or without object pooling works with ConcurrentHashMap, but only without object pooling works for NBHM.

I fully anticipate that I may be doing something stupid, but sadly I cannot yet ascertain what that is :-( If so, apologies in advance for wasting your time. Also the fact that I get the expected behaviour with `ConcurrentHashMap` but not with `NonBlockingHashMap`, even in a single-threaded environment makes me wonder if I can do such key object recycling with NBHM?

I did note that NBHM seems to memoize hashes, but I could not determine if that was preventing my key recycling from working as I would expect.

**Comment by franz1981** [comment] 2019-03-19 08:11
@adamretter I would add a `Unsafe:.storeFence` right after initializing a recycled entry and before putting it into the map

**Comment by adamretter** [comment] 2019-03-19 08:45
@franz1981 I am not certain no. I have been studying it for a couple days now, *I think* it is correct, but I may well have missed something. I do freely admit, the error is likely to be in my code rather than jctools ;-)

Btw - I did already try an alternative pool implementation using a `Deque` - https://github.com/adamretter/nonblockinghashmaptest/blob/master/src/main/java/nbhm/Test2.java#L16 and like you I still get an error, but upon a different event. Again, I have been staring at that code too and running the debugger between Test1 and Test2, yet I can't figure out why you get slightly different errors.

**Comment by cliffclick** [comment] 2019-03-19 17:30
The HashMap contract is pretty clear; the key.hashCode and key.equals() 
calls cannot change behavior over time.  Other fields in the keys are 
irrelevant (from a HashMap POV) and can be changed willy-nilly.

NBHM depends on the key behavior being invariant over time, *even after 
a key is removed* - NBHM cannot actually remove any keys directly, but 
has to copy the entire map ("resize") to drop any keys.

Since you are pooling objects, I suspect (not tested), this is a case of 
a key in the Map which gets removed (from the user POV) but is still in 
the NBHM as a placeholder and the key changed - which breaks the key 
invariant NBHM is depending on.

The reason NBHM cannot remove keys instantly is tied directly to the 
non-blocking aspect; 2 memory words are being written by 2 racing 
threads - the Key and the Value.  There's no way to avoid accidentally 
allowing a 3rd thread from mis-associating the wrong Key and Value if 
the Key word ever changes.  So the Key fields in NBHM literally make a 
one-time null->Key transition, and can **never** change again.  Instead, 
the entire K/V mapping is periodically copied over to a new K/V mapping, 
dropping the dead Keys alone the way.

If you want to Pool objects in this manner, I suggest you use CHM.... 
but I also suggest you *heavily profile* both techniques & both maps 
(NBHM without pooling, CHM with and without pooling).  There are a very 
few performance domains where the pooling will matter... but when it 
matters, it can matter by 10x.  Same for the non-blocking vs CHM; only 
rarely matters (very intense r/w loads on high core counts), but when it 
matters it can matter alot.

Cliff

**Comment by nitsanw** [comment] 2019-05-28 14:30
I'm not going to tackle this issue until JCTools drops JDK6/7 support.

**Closed** 2024-01-25 07:40 UTC
Labels: bug, wontfix, JDK8Min

**Comment by adamretter** [comment] 2024-01-25 08:07
I just wanted to thank everyone that participated in helping me here - thank you :-)
